# Generated by Django 4.0 on 2023-07-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0010_rename_nombre_turno_nom_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
