# Generated by Django 4.0 on 2023-07-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0012_alter_libro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(upload_to='images'),
        ),
    ]
